//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassEngineLibrary.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LanguageResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LanguageResource() {
        }

        public static object Plus { 
                get {
                    return ResourceManager.GetString("Plus", resourceCulture);
                }
            }
        
        public static object Minus
        {
            get
            {
                return ResourceManager.GetString("Minus", resourceCulture);
            }
        }
        public static object Time { 
                get {
                    return ResourceManager.GetString("Time", resourceCulture);
                }
            }
        
        public static object DividedBy
        {
            get
            {
                return ResourceManager.GetString("DividedBy", resourceCulture);
            }
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ClassEngineLibrary.Properties.LanguageResource", typeof(LanguageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write a valid first number :.
        /// </summary>
        public static string ValidFirstNumber {
            get {
                return ResourceManager.GetString("ValidFirstNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write a valid operation (+, -, *, /) or (plus, minus, time, divide by).
        /// </summary>
        public static string ValidOp {
            get {
                return ResourceManager.GetString("ValidOp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write a valid second number :.
        /// </summary>
        public static string ValidSecondNumber {
            get {
                return ResourceManager.GetString("ValidSecondNumber", resourceCulture);
            }
        }
    }
}
